#!/usr/bin/env bash
set -e

# Generated by setup.sh.
# Add CREATE USER / CREATE DATABASE statements for your services.

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    -- Example:
    -- CREATE USER app_user WITH PASSWORD 'change_me';
    -- CREATE DATABASE app_db;
    -- GRANT ALL PRIVILEGES ON DATABASE app_db TO app_user;
    -- ALTER DATABASE app_db OWNER TO app_user;
EOSQL
